# Generated by Django 5.1.6 on 2025-02-26 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('room_id', models.CharField(blank=True, max_length=24, primary_key=True, serialize=False)),
                ('current_turn', models.CharField(choices=[('player1', 'Player 1'), ('player2', 'Player 2')], default='player1', max_length=64)),
                ('fen', models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'Active'), ('ended', 'Ended')], default='waiting', max_length=10)),
                ('winner', models.CharField(blank=True, choices=[('player1', 'Player 1'), ('player2', 'Player 2')], max_length=64, null=True)),
                ('over_type', models.CharField(blank=True, choices=[('draw', 'Draw'), ('resign', 'Resign'), ('checkmate', 'Checkmate')], max_length=20, null=True)),
                ('format', models.CharField(choices=[('classic', 'Classic'), ('rapid', 'Rapid'), ('bliz', 'Bliz'), ('bullet', 'Bullet'), ('custom', 'Custom')], default='rapid', max_length=10)),
                ('player1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player1', to=settings.AUTH_USER_MODEL)),
                ('player2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clock',
            fields=[
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='game_clock', serialize=False, to='chess_app.game')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('total_time', models.IntegerField(default=900000, help_text='Total time in milliseconds')),
                ('incremental_time', models.IntegerField(default=0, help_text='Incremental time in milliseconds')),
                ('clock1', models.IntegerField(default=900000, help_text='Player1 remaining time in ms')),
                ('clock2', models.IntegerField(default=900000, help_text='Player2 remaining time in ms')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.CharField(help_text='move in SAN', max_length=10)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_moves', to='chess_app.game')),
            ],
        ),
    ]
