# Generated by Django 5.1.6 on 2025-03-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0002_game_player1_color_game_player2_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='player1_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=16),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_status',
            field=models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected')], default='disconnected', max_length=16),
        ),
    ]
