# Generated by Django 5.1.6 on 2025-03-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chess_app', '0003_game_player1_status_game_player2_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='player1_status',
        ),
        migrations.RemoveField(
            model_name='game',
            name='player2_status',
        ),
        migrations.AddField(
            model_name='game',
            name='player1_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='player2_connected',
            field=models.BooleanField(default=False),
        ),
    ]
